In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("cars.csv")
df.head(4)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000

In [6]:
df.shape

(8128, 5)

In [8]:
df.isnull().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [10]:
#Find the average selling price of cars grouped by brand.

In [20]:
brand_group=df.groupby('brand')['selling_price'].mean()

In [22]:
brand_group

brand
Ambassador       1.240000e+05
Ashok            3.000000e+05
Audi             2.612200e+06
BMW              4.109917e+06
Chevrolet        2.738675e+05
Daewoo           7.700000e+04
Datsun           3.146000e+05
Fiat             2.960638e+05
Force            8.875000e+05
Ford             5.166826e+05
Honda            5.961780e+05
Hyundai          4.585544e+05
Isuzu            1.942000e+06
Jaguar           2.915465e+06
Jeep             2.149613e+06
Kia              1.504500e+06
Land             3.608333e+06
Lexus            5.150000e+06
MG               1.783333e+06
Mahindra         6.232241e+05
Maruti           4.030757e+05
Mercedes-Benz    2.470444e+06
Mitsubishi       8.175000e+05
Nissan           4.654074e+05
Opel             6.800000e+04
Peugeot          5.700000e+04
Renault          4.626184e+05
Skoda            6.077238e+05
Tata             3.574331e+05
Toyota           9.599467e+05
Volkswagen       4.988172e+05
Volvo            3.272015e+06
Name: selling_price, dtype: float64

In [24]:
#Find the maximum km_driven for each fuel type.

In [30]:
max_km=df.groupby('fuel')['km_driven'].max()

In [32]:
max_km

fuel
CNG        270000
Diesel    1500000
LPG        300000
Petrol    2360457
Name: km_driven, dtype: int64

In [50]:
#Count how many cars are owned by each owner type.

In [72]:
car=df.groupby('owner')['brand'].count()

In [74]:
car

owner
First Owner             5289
Fourth & Above Owner     174
Second Owner            2105
Test Drive Car             5
Third Owner              555
Name: brand, dtype: int64

In [76]:
#Find minimum, maximum, and average selling price for each brand.

In [83]:
aggr=df.groupby('brand')['selling_price'].agg(['min','max','mean'])

In [85]:
aggr

                   min       max          mean
brand
Ambassador       75000    200000  1.240000e+05
Ashok           300000    300000  3.000000e+05
Audi            730000   6523000  2.612200e+06
BMW             480000   7200000  4.109917e+06
Chevrolet        45000   1295000  2.738675e+05
Daewoo           45000    100000  7.700000e+04
Datsun          150000    590000  3.146000e+05
Fiat             70000    700000  2.960638e+05
Force           555000   1050000  8.875000e+05
Ford             55000   3250000  5.166826e+05
Honda            50000   2125000  5.961780e+05
Hyundai          30000   1950000  4.585544e+05
Isuzu          1160000   2700000  1.942000e+06
Jaguar         2000000   3500000  2.915465e+06
Jeep           1325000   4100000  2.149613e+06
Kia             643000   1900000  1.504500e+06
Land           1650000   4500000  3.608333e+06
Lexus          5150000   5150000  5.150000e+06
MG             1700000   1900000  1.783333e+06
Mahindra        120000   1800000  6.232241e+05
Maruti           29999   1200000  4.030757e+05
Mercedes-Benz   400000   6000000  2.470444e+06
Mitsubishi      150000   1950000  8.175000e+05
Nissan          110000   1200000  4.654074e+05
Opel             68000     68000  6.800000e+04
Peugeot          57000     57000  5.700000e+04
Renault         200000   1265000  4.626184e+05
Skoda           100000   3251000  6.077238e+05
Tata             40000   1700000  3.574331e+05
Toyota          100000   3500000  9.599467e+05
Volkswagen      210000   2150000  4.988172e+05
Volvo          1200000  10000000  3.272015e+06

In [ ]:
#Show total cars and average km_driven grouped by fuel.

In [91]:
totalAvg=df.groupby('fuel').agg(totcar=("brand",'count'),km_avg=("km_driven",'mean') )

In [93]:
totalAvg

        totcar        km_avg
fuel
CNG         57  68288.438596
Diesel    4402  83677.137210
LPG         38  89174.105263
Petrol    3631  52840.861746

In [95]:
#Find the average price of cars grouped by fuel and owner.

In [97]:
avgPrice=df.groupby(['fuel','owner'])['selling_price'].mean()

In [99]:
avgPrice

fuel    owner
CNG     First Owner             3.540293e+05
        Fourth & Above Owner    1.895000e+05
        Second Owner            2.330556e+05
        Third Owner             1.823333e+05
Diesel  First Owner             9.792325e+05
        Fourth & Above Owner    3.170056e+05
        Second Owner            4.912978e+05
        Test Drive Car          1.350000e+06
        Third Owner             3.779866e+05
LPG     First Owner             2.508824e+05
        Fourth & Above Owner    1.350000e+05
        Second Owner            1.640714e+05
        Third Owner             1.568000e+05
Petrol  First Owner             5.668341e+05
        Fourth & Above Owner    1.310488e+05
        Second Owner            2.586365e+05
        Test Drive Car          5.167250e+06
        Third Owner             1.846488e+05
Name: selling_price, dtype: float64

In [101]:
#For each brand and fuel type, find the maximum km_driven.

In [103]:
max_km=df.groupby(['brand','fuel'])['km_driven'].max()